[package]
edition = "2021"
name = "alpen-reth-evm"
version = "0.3.0-alpha.1"

[lints]
workspace = true

[dependencies]
alpen-ee-params.workspace = true
alpen-reth-primitives.workspace = true
strata-bridge-params.workspace = true
strata-crypto.workspace = true
strata-identifiers.workspace = true
strata-ol-bridge-types.workspace = true
strata-primitives.workspace = true

alloy-consensus.workspace = true
alloy-eips.workspace = true
alloy-rpc-types-engine.workspace = true
alloy-sol-types.workspace = true
reth-chainspec.workspace = true
reth-ethereum-primitives.workspace = true
reth-evm.workspace = true
reth-evm-ethereum.workspace = true
reth-primitives.workspace = true
reth-primitives-traits.workspace = true
revm.workspace = true
revm-primitives.workspace = true
thiserror.workspace = true

[dev-dependencies]
secp256k1.workspace = true
strata-crypto.workspace = true
proptest.workspace = true
