//! Typed table schema and key/value codec traits.
//!
//! These mirror the shape of the `typed-sled` codec traits so that the same
//! encoding conventions (borsh, `strata-codec`, big-endian integer keys) carry
//! over to MDBX-backed tables. Values decode to owned types (copy-out of the
//! transaction), which sidesteps the zero-copy lifetime hazards of holding a
//! borrowed view across a transaction boundary.

use std::error::Error;

/// Boxed, thread-safe error used as the source of a [`CodecError`].
pub type BoxError = Box<dyn Error + Send + Sync + 'static>;

/// Failure to encode or decode a key or value for a [`Schema`].
#[derive(Debug, thiserror::Error)]
pub enum CodecError {
    /// Encoding a key or value failed.
    #[error("failed to encode value for table `{schema}`")]
    Encode {
        /// The table whose codec failed.
        schema: &'static str,
        /// The underlying encoder error.
        #[source]
        source: BoxError,
    },
    /// Decoding a key or value failed.
    #[error("failed to decode value for table `{schema}`")]
    Decode {
        /// The table whose codec failed.
        schema: &'static str,
        /// The underlying decoder error.
        #[source]
        source: BoxError,
    },
}

impl CodecError {
    /// Constructs an [`CodecError::Encode`] for `schema` from any boxable error.
    pub fn encode(schema: &'static str, source: impl Into<BoxError>) -> Self {
        Self::Encode {
            schema,
            source: source.into(),
        }
    }

    /// Constructs an [`CodecError::Decode`] for `schema` from any boxable error.
    pub fn decode(schema: &'static str, source: impl Into<BoxError>) -> Self {
        Self::Decode {
            schema,
            source: source.into(),
        }
    }
}

/// A typed MDBX table: a named sub-database with a key and value type.
///
/// Implementers are usually generated by the [`define_table!`](crate::define_table)
/// family of macros. [`Schema::NAME`] is the MDBX sub-database name and must be
/// unique within an environment.
pub trait Schema: Sized + Send + Sync + 'static {
    /// The MDBX sub-database name. Must be unique within an environment.
    const NAME: &'static str;

    /// Whether the table stores multiple values per key (MDBX `DUP_SORT`).
    const DUP_SORT: bool = false;

    /// The key type; encoded via its [`KeyCodec`] impl.
    type Key: KeyCodec<Self>;

    /// The value type; encoded via its [`ValueCodec`] impl.
    type Value: ValueCodec<Self>;
}

/// Encodes and decodes a [`Schema`]'s key to and from bytes.
///
/// Key encoding determines cursor order (MDBX orders keys lexicographically by
/// their bytes), so integer keys that must sort numerically should use a
/// big-endian codec.
pub trait KeyCodec<S: Schema>: Sized {
    /// Encodes the key to its on-disk byte representation.
    fn encode_key(&self) -> Result<Vec<u8>, CodecError>;

    /// Decodes the key from its on-disk byte representation.
    fn decode_key(bytes: &[u8]) -> Result<Self, CodecError>;
}

/// Encodes and decodes a [`Schema`]'s value to and from bytes.
pub trait ValueCodec<S: Schema>: Sized {
    /// Encodes the value to its on-disk byte representation.
    fn encode_value(&self) -> Result<Vec<u8>, CodecError>;

    /// Decodes the value from its on-disk byte representation.
    fn decode_value(bytes: &[u8]) -> Result<Self, CodecError>;
}
