[package]
edition = "2021"
name = "alpen-reth-witness"
version = "0.3.0-alpha.1"

[lints]
workspace = true

[dependencies]
# Internal
alpen-ee-common.workspace = true
strata-acct-types.workspace = true
strata-codec.workspace = true
strata-evm-ee.workspace = true

# External
alloy-consensus.workspace = true
alloy-primitives.workspace = true
eyre.workspace = true
reth-ethereum-primitives.workspace = true
reth-provider.workspace = true
reth-revm.workspace = true
reth-trie.workspace = true
reth-trie-common = { workspace = true, features = ["eip1186"] }
revm-primitives.workspace = true
rsp-mpt.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
