[package]
edition.workspace = true
name = "alpen-reth-statediff"
version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
alloy-genesis.workspace = true
alloy-primitives.workspace = true
alloy-trie.workspace = true
revm.workspace = true
revm-primitives.workspace = true
rsp-mpt.workspace = true
serde.workspace = true
strata-codec.workspace = true
strata-da-framework.workspace = true
strata-identifiers.workspace = true
thiserror.workspace = true

[dev-dependencies]
bincode.workspace = true
proptest.workspace = true
serde_json.workspace = true

[features]
serde = []
