[package]
description = "Consolidated top-level Alpen chain params artifact."
edition = "2021"
name = "alpen-ee-params"
version = "0.3.0-alpha.1"

[lints]
workspace = true

[dependencies]
alpen-chainspec.workspace = true
strata-acct-types.workspace = true
strata-bridge-params.workspace = true
strata-l1-txfmt.workspace = true

alloy-genesis.workspace = true
num_enum.workspace = true
reth-chainspec.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
