[package]
edition = "2021"
name = "alpen-ee-database"
version = "0.3.0-alpha.1"

[lints]
workspace = true

[dependencies]
alpen-db-store-mdbx.workspace = true
alpen-ee-common.workspace = true
alpen-reth-db.workspace = true
bitcoin.workspace = true
strata-acct-types.workspace = true
strata-db-macros.workspace = true
strata-db-store-sled.workspace = true
strata-db-types.workspace = true
strata-ee-acct-types.workspace = true
strata-ee-chain-types.workspace = true
strata-identifiers.workspace = true
strata-paas.workspace = true
strata-storage.workspace = true
strata-storage-common.workspace = true
zkaleido.workspace = true

async-trait.workspace = true
bincode.workspace = true
borsh.workspace = true
eyre.workspace = true
sled.workspace = true
ssz.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
typed-sled.workspace = true

[dev-dependencies]
alpen-ee-common = { workspace = true, features = ["test-utils"] }
strata-storage = { workspace = true, features = ["test-utils"] }
