[package]
edition = "2021"
name = "alpen-ee-rpc-server"
version = "0.3.0-alpha.1"

[lints]
workspace = true

[dependencies]
alpen-ee-common.workspace = true
alpen-ee-rpc-api.workspace = true

alloy-primitives.workspace = true
async-trait.workspace = true
jsonrpsee = { workspace = true, features = ["server"] }
reth-node-builder.workspace = true
reth-provider.workspace = true
reth-rpc-layer.workspace = true
strata-identifiers.workspace = true
tokio.workspace = true
tower.workspace = true

[dev-dependencies]
alpen-ee-rpc-api = { workspace = true, features = ["client"] }
http.workspace = true
jsonrpsee = { workspace = true, features = ["http-client"] }
tempfile.workspace = true
