#![no_main]
zkaleido_sp1_guest_env::entrypoint!(main);

use alpen_ee_params::AlpenParams;
use strata_predicate::{PredicateKey, PredicateTypeId};
use strata_proofimpl_alpen_acct::process_ee_acct_update;
use zkaleido_sp1_guest_env::Sp1ZkVmEnv;

/// Compile-time-baked build artifacts generated by `build.rs`: the chunk
/// guest's Groth16 predicate condition bytes and the canonical `AlpenParams`
/// JSON. Not zkVM input — see
/// `strata_proofimpl_alpen_acct::process_ee_acct_update` for why.
mod predicates {
    include!(concat!(env!("CARGO_MANIFEST_DIR"), "/../generated/predicates.rs"));
}

mod alpen_params {
    include!(concat!(env!("CARGO_MANIFEST_DIR"), "/../generated/alpen_params.rs"));
}

/// Constructs the chunk proof predicate key from the Groth16 predicate
/// condition bytes that `build.rs` embeds in `predicates.rs`.
fn chunk_predicate_key() -> PredicateKey {
    PredicateKey::new(
        PredicateTypeId::Sp1Groth16,
        predicates::ALPEN_CHUNK_PREDICATE_CONDITION_BYTES.to_vec(),
    )
}

fn canonical_alpen_params() -> AlpenParams {
    serde_json::from_str(alpen_params::ALPEN_PARAMS_JSON)
        .expect("embedded canonical alpen params must parse")
}

fn main() {
    let key = chunk_predicate_key();
    let params = canonical_alpen_params();
    process_ee_acct_update(&Sp1ZkVmEnv, &params, &key)
}
