[package]
edition.workspace = true
name = "alpen-da-types"
version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
alpen-reth-statediff.workspace = true
strata-codec.workspace = true
strata-crypto.workspace = true

bitcoin.workspace = true
rkyv.workspace = true
rkyv_impl.workspace = true
