# alpen-client config for the "fn" container in docker-compose-p2p-test.yml.
#
# Same as p2p-test-node-a.toml, but forwards user-submitted transactions to
# the other container. See that file for why sequencer_pubkey is a
# placeholder.

mode = "full_node"

[ol]
source = "dummy"

[full_node]
sequencer_pubkey = "1b84c5567b126440995d3ed5aaba0565d71e1834604819ff9c17f5e9d5dd078f"
sequencer_http_url = "http://alpen-client:8545"
