[package]
edition = "2021"
name = "guest-sp1-alpen-acct-v0"
version = "0.1.0"

[workspace]

[dependencies]
alpen-ee-params = { path = "../../../crates/alpen-ee/params" }
serde_json = "1.0.94"
strata-predicate = { git = "https://github.com/alpenlabs/strata-common", tag = "v0.3.0", features = [
  "sp1-groth16",
] }
strata-proofimpl-alpen-acct = { path = "../../../crates/proof-impl/alpen-acct" }
zkaleido-sp1-guest-env = { git = "https://github.com/alpenlabs/zkaleido", tag = "v0.3.0", features = [
  "zkvm-verify",
] }

[patch.crates-io]
secp256k1 = { git = "https://github.com/sp1-patches/rust-secp256k1", tag = "patch-0.29.1-sp1-6.0.0" }
secp256k1-sys = { git = "https://github.com/sp1-patches/rust-secp256k1", tag = "patch-0.29.1-sp1-6.0.0" }
sha2 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", package = "sha2", tag = "patch-sha2-0.10.9-sp1-6.0.0" }
substrate-bn = { git = "https://github.com/sp1-patches/bn", tag = "patch-0.6.0-sp1-6.0.0-substrate-bn" }
sha3 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", package = "sha3", tag = "patch-sha3-0.10.8-sp1-6.0.0" }
k256 = { git = "https://github.com/sp1-patches/elliptic-curves", tag = "patch-k256-13.4-sp1-6.0.0" }
