//! Build script for the SP1 guest programs (`guest-alpen-chunk`, `guest-alpen-acct`).
//!
//! Guests are built sequentially in dependency order: the account guest verifies chunk
//! proofs, so the chunk guest's Groth16 verifying-key condition bytes are code-generated
//! into `guest-alpen-acct/src/vks.rs` between the two builds. Compiled ELFs are emitted
//! to `<crate>/elfs/`, a stable location that survives `cargo clean` and that `lib.rs`
//! and CI reference directly.
//!
//! Building the guests requires the SP1 toolchain; set `SP1_SKIP_PROGRAM_BUILD=true` to
//! skip guest compilation entirely (clippy is skipped automatically).
//!
//! # Features
//!
//! - **`docker-build`** — compile the guests inside Docker via `build_program_with_args` for
//!   reproducible ELFs. The output location is unchanged.
//!
//! # Environment variables
//!
//! - **`SP1_SKIP_PROGRAM_BUILD`** — when set to `true`, skip guest compilation (the same variable
//!   sp1-build honors internally).
//! - **`ZKVM_MOCK`** — when set to `1`/`true`, guests are built with the `mock-verify` feature so
//!   recursive proof verification becomes a no-op. Never use in production.

use std::{env, fs, path::Path};

use sp1_build::{build_program_with_args, BuildArgs};
use sp1_sdk::{
    blocking::{Prover, ProverClient},
    HashableKey, ProvingKey,
};
use sp1_verifier::{GROTH16_VK_BYTES, VK_ROOT_BYTES};
use zkaleido_sp1_groth16_verifier::SP1Groth16Verifier;

const ELFS_DIR: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/elfs");

const ALPEN_CHUNK: &str = "guest-alpen-chunk";
const ALPEN_ACCT: &str = "guest-alpen-acct";

fn main() {
    println!("cargo:rerun-if-env-changed=SP1_SKIP_PROGRAM_BUILD");
    println!("cargo:rerun-if-env-changed=ZKVM_MOCK");

    if skip_elf_build() {
        println!(
            "cargo:warning=SP1_SKIP_PROGRAM_BUILD set or clippy detected; skipping guest build"
        );
        return;
    }

    let features = guest_features();

    // The account guest embeds the chunk guest's verifying key, so the chunk
    // guest must be built (and its VK derived) first.
    build_guest(ALPEN_CHUNK, &features);
    write_acct_vks(&chunk_vk_condition());
    build_guest(ALPEN_ACCT, &features);
}

fn build_guest(program: &str, features: &[String]) {
    let build_args = BuildArgs {
        output_directory: Some(ELFS_DIR.to_owned()),
        elf_name: Some(format!("{program}.elf")),
        features: features.to_vec(),
        #[cfg(feature = "docker-build")]
        docker: true,
        // Override the guest's workspace root with the repo root so Docker
        // mounts the entire workspace and the guest can import local crates.
        #[cfg(feature = "docker-build")]
        workspace_directory: Some("../../".to_owned()),
        ..Default::default()
    };
    build_program_with_args(program, build_args);
}

/// Derives the chunk guest's Groth16 verifying-key condition bytes from its
/// freshly built ELF. These are the canonical uncompressed encoding of an
/// [`SP1Groth16Verifier`] that the runtime `Sp1Groth16` predicate verifier in
/// `strata-predicate` decodes via `SP1Groth16Verifier::parse`.
fn chunk_vk_condition() -> Vec<u8> {
    let elf_path = Path::new(ELFS_DIR).join(format!("{ALPEN_CHUNK}.elf"));
    let elf = fs::read(&elf_path)
        .unwrap_or_else(|e| panic!("read built ELF {}: {e}", elf_path.display()));

    let prover = ProverClient::builder().cpu().build();
    let pk = prover
        .setup(elf.into())
        .unwrap_or_else(|e| panic!("sp1 key setup for {ALPEN_CHUNK}: {e}"));
    let vkey_hash = pk.verifying_key().bytes32_raw();

    let verifier = SP1Groth16Verifier::load(&GROTH16_VK_BYTES, vkey_hash, *VK_ROOT_BYTES, true)
        .unwrap_or_else(|e| panic!("load SP1 Groth16 verifier: {e}"));
    verifier.to_uncompressed_bytes()
}

/// Writes the chunk guest's VK condition into `guest-alpen-acct/src/vks.rs` so
/// the account guest can construct the chunk predicate key at compile time
/// without pulling in heavy SP1 SDK dependencies.
fn write_acct_vks(condition: &[u8]) {
    let content = format!(
        "//! Generated by `build.rs` — do not edit.\n\
         pub const GUEST_ALPEN_CHUNK_VK_CONDITION: &[u8] = &{condition:?};\n"
    );
    let vks_path = Path::new(ALPEN_ACCT).join("src").join("vks.rs");
    fs::write(&vks_path, content).unwrap_or_else(|e| panic!("write {}: {e}", vks_path.display()));
}

/// Returns the guest cargo features implied by `ZKVM_MOCK`.
fn guest_features() -> Vec<String> {
    let mock = env::var("ZKVM_MOCK")
        .map(|v| v == "1" || v.eq_ignore_ascii_case("true"))
        .unwrap_or(false);

    if mock {
        println!("cargo:warning=ZKVM_MOCK is set. ----------------------------------------");
        println!("cargo:warning=ZKVM_MOCK is set. This should never be used in production.");
        println!("cargo:warning=ZKVM_MOCK is set. ----------------------------------------");
        vec!["mock-verify".to_owned()]
    } else {
        vec!["zkvm-verify".to_owned()]
    }
}

/// Returns `true` when sp1-build itself would skip the build — under
/// `SP1_SKIP_PROGRAM_BUILD=true` or `cargo clippy`.
fn skip_elf_build() -> bool {
    let skip_env = env::var("SP1_SKIP_PROGRAM_BUILD")
        .map(|v| v.eq_ignore_ascii_case("true"))
        .unwrap_or(false);
    let is_clippy = env::var("RUSTC_WORKSPACE_WRAPPER")
        .map(|v| v.contains("clippy-driver"))
        .unwrap_or(false);
    skip_env || is_clippy
}
