//! Build script for the SP1 guest programs (`guest-alpen-chunk`, `guest-alpen-acct`).
//!
//! Guests are built sequentially in dependency order: the account guest verifies chunk
//! proofs, so the chunk guest's Groth16 predicate condition bytes are code-generated
//! into `guest-alpen-acct/src/predicates.rs` between the two builds. Compiled ELFs are
//! emitted to `<crate>/elfs/`, a stable location that survives `cargo clean` and that
//! `lib.rs` and CI reference directly.
//!
//! Building the guests requires the SP1 toolchain; set `SP1_SKIP_PROGRAM_BUILD=true` to
//! skip guest compilation entirely (clippy is skipped automatically).
//!
//! # Features
//!
//! - **`docker-build`** — compile the guests inside Docker via `build_program_with_args` for
//!   reproducible ELFs. The output location is unchanged.
//!
//! # Environment variables
//!
//! - **`SP1_SKIP_PROGRAM_BUILD`** — when set to `true`, skip guest compilation (the same variable
//!   sp1-build honors internally).

use std::{env, fs, path::Path};

use sp1_build::{build_program_with_args, BuildArgs};
use sp1_sdk::{
    blocking::{Prover, ProverClient},
    HashableKey, ProvingKey,
};
use sp1_verifier::{GROTH16_VK_BYTES, VK_ROOT_BYTES};
use zkaleido_sp1_groth16_verifier::SP1Groth16Verifier;

const ELFS_DIR: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/elfs");

const ALPEN_CHUNK: &str = "guest-alpen-chunk";
const ALPEN_ACCT: &str = "guest-alpen-acct";

fn main() {
    println!("cargo:rerun-if-env-changed=SP1_SKIP_PROGRAM_BUILD");

    if skip_elf_build() {
        println!(
            "cargo:warning=SP1_SKIP_PROGRAM_BUILD set or clippy detected; skipping guest build"
        );
        return;
    }

    // The account guest embeds the chunk guest's predicate condition, so the
    // chunk guest must be built (and its VK derived) first.
    build_guest(ALPEN_CHUNK);
    write_acct_predicates(&chunk_predicate_condition());
    build_guest(ALPEN_ACCT);
}

fn build_guest(program: &str) {
    let build_args = BuildArgs {
        output_directory: Some(ELFS_DIR.to_owned()),
        elf_name: Some(format!("{program}.elf")),
        #[cfg(feature = "docker-build")]
        docker: true,
        // Override the guest's workspace root with the repo root so Docker
        // mounts the entire workspace and the guest can import local crates.
        #[cfg(feature = "docker-build")]
        workspace_directory: Some("../../".to_owned()),
        ..Default::default()
    };
    build_program_with_args(program, build_args);
}

/// Derives the condition bytes of the chunk guest's `Sp1Groth16` predicate
/// from its freshly built ELF. These are the canonical uncompressed encoding
/// of an [`SP1Groth16Verifier`] (embedding the guest's verifying key) that the
/// runtime predicate verifier in `strata-predicate` decodes via
/// `SP1Groth16Verifier::parse`.
fn chunk_predicate_condition() -> Vec<u8> {
    let elf_path = Path::new(ELFS_DIR).join(format!("{ALPEN_CHUNK}.elf"));
    let elf = fs::read(&elf_path)
        .unwrap_or_else(|e| panic!("read built ELF {}: {e}", elf_path.display()));

    let prover = ProverClient::builder().cpu().build();
    let pk = prover
        .setup(elf.into())
        .unwrap_or_else(|e| panic!("sp1 key setup for {ALPEN_CHUNK}: {e}"));
    let vkey_hash = pk.verifying_key().bytes32_raw();

    let verifier = SP1Groth16Verifier::load(&GROTH16_VK_BYTES, vkey_hash, *VK_ROOT_BYTES, true)
        .unwrap_or_else(|e| panic!("load SP1 Groth16 verifier: {e}"));
    verifier.to_uncompressed_bytes()
}

/// Writes the chunk guest's predicate condition into
/// `guest-alpen-acct/src/predicates.rs` so the account guest can construct the
/// chunk predicate key at compile time without pulling in heavy SP1 SDK
/// dependencies. The predicate type id stays hard-coded in the guest source;
/// only the build-derived condition bytes are generated.
fn write_acct_predicates(condition: &[u8]) {
    let content = format!(
        "//! Generated by `build.rs` — do not edit.\n\
         pub const ALPEN_CHUNK_PREDICATE_CONDITION_BYTES: &[u8] = &{condition:?};\n"
    );
    let predicates_path = Path::new(ALPEN_ACCT).join("src").join("predicates.rs");
    fs::write(&predicates_path, content)
        .unwrap_or_else(|e| panic!("write {}: {e}", predicates_path.display()));
}

/// Returns `true` when sp1-build itself would skip the build — under
/// `SP1_SKIP_PROGRAM_BUILD=true` or `cargo clippy`.
fn skip_elf_build() -> bool {
    let skip_env = env::var("SP1_SKIP_PROGRAM_BUILD")
        .map(|v| v.eq_ignore_ascii_case("true"))
        .unwrap_or(false);
    let is_clippy = env::var("RUSTC_WORKSPACE_WRAPPER")
        .map(|v| v.contains("clippy-driver"))
        .unwrap_or(false);
    skip_env || is_clippy
}
