[package]
edition.workspace = true
name = "alpen-ee-exec-chain"
version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
alpen-ee-common.workspace = true
strata-acct-types.workspace = true

anyhow.workspace = true
eyre.workspace = true
serde.workspace = true
strata-service.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
strata-identifiers.workspace = true
strata-ee-acct-types.workspace = true
strata-ee-chain-types.workspace = true
alpen-ee-common = { workspace = true, features = ["test-utils"] }
alpen-ee-params.workspace = true
