[package]
edition = "2021"
name = "strata-zkvm-hosts"
version = "0.3.0-alpha.1"

[lints]
workspace = true

[dependencies]
# sp1
strata-sp1-guest-builder = { path = "../../../provers/sp1", optional = true }
tokio = { workspace = true, optional = true }
zkaleido-sp1-host = { workspace = true, optional = true }

[features]
default = []
sp1 = ["dep:zkaleido-sp1-host", "dep:tokio"]
sp1-builder = ["sp1", "dep:strata-sp1-guest-builder"]
