[package]
name = "alpen-proof-chunk"
version.workspace = true
edition = "2024"
license.workspace = true
repository.workspace = true

[dependencies]
alpen-chain-types.workspace = true
alpen-chunk-runtime.workspace = true
alpen-evm-ee.workspace = true
alpen-params.workspace = true
strata-predicate.workspace = true

k256.workspace = true
rkyv.workspace = true
ssz.workspace = true
zkaleido.workspace = true
zkaleido-native-adapter.workspace = true

[dev-dependencies]
alpen-params = { workspace = true, features = ["test-utils"] }
strata-acct-types.workspace = true
strata-codec.workspace = true
alpen-acct-types.workspace = true

reth-primitives-traits.workspace = true
rsp-client-executor.workspace = true
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true
