[package]
edition = "2021"
name = "alpen-ee-da-l1-extraction"
version = "0.3.0-alpha.1"

[lints]
workspace = true

[dependencies]
alpen-ee-da-types.workspace = true
strata-btc-types.workspace = true
strata-common = { workspace = true, features = ["async"] }
strata-identifiers.workspace = true
strata-l1-envelope-fmt.workspace = true
strata-l1-txfmt.workspace = true

bitcoin.workspace = true
bitcoind-async-client.workspace = true
futures.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
strata-l1-envelope-fmt = { workspace = true, features = ["test-utils"] }
